apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 32112
  type: LoadBalancer


