apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env: []
        image: grafana/grafana:latest
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards/k8s-addons-starboard-operator.json
            name: dashboards-k8s-addons-starboard-operator
            readOnly: true
            subPath: k8s-addons-starboard-operator.json
          - mountPath: /etc/grafana/provisioning/dashboards/default.yaml
            name: grafana-dashboards-provider
            readOnly: false
            subPath: default.yaml
          - mountPath: /etc/grafana/provisioning/dashboards/k8s-system-api-server.json
            name: dashboards-k8s-system-api-server
            readOnly: false
            subPath: k8s-system-api-server.json
#        volumeMounts:
#        - mountPath: /var/lib/grafana
#          name: grafana-storage
#          readOnly: false
#      nodeSelector:
#        node-type: worker
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: dashboards-k8s-addons-starboard-operator
          configMap:
              defaultMode: 420
              name: dashboards-k8s-addons-starboard-operator
        - name: grafana-dashboards-provider
          configMap:
              defaultMode: 420
              name: grafana-dashboards-provider
        - name: dashboards-k8s-system-api-server
          configMap:
              defaultMode: 420
              name: dashboards-k8s-system-api-server
        - name: dashboards-k8s-system-coredns
          configMap:
              defaultMode: 420
              name: dashboards-k8s-system-coredns
        - name: dashboards-k8s-views-global
          configMap:
              defaultMode: 420
              name: dashboards-k8s-views-global
        - name: dashboards-k8s-views-namespaces
          configMap:
              defaultMode: 420
              name: dashboards-k8s-views-namespaces
        - name: dashboards-k8s-views-nodes
          configMap:
              defaultMode: 420
              name: dashboards-k8s-views-nodes
        - name: dashboards-k8s-views-pods
          configMap:
              defaultMode: 420
              name: dashboards-k8s-views-pods
#      volumes:
#        - name: grafana-storage
#          persistentVolumeClaim:
#            claimName: longhorn-grafana-pvc
