apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: rustoleum76/webservice:latest
        ports:
        - containerPort: 8080



