apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  selector:
    app: webservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32113
  type: LoadBalancer


